### PR TITLE
Add notebooks with improved quality 

### PR DESCRIPTION
**Pull request by mangalp**
Changes include:

i) percentage of images changed to number of images,
ii) add display of results,
iii) add tables from wiki directly into notebooks for direct comparison

### CODE REVIEW

**Comment by frauzufall** [comment]
why is the one hot encoded background empty in the new notebook?

**Comment by mangalp** [comment]
> why is the one hot encoded background empty in the new notebook?

This holds true for the flywing data, it has all the cells as foreground and the border is 1 pixel thick in the GT annotations, so the background is empty.

**Comment by frauzufall** [comment]
:-D that makes sense. thanks for explaining.

**Comment by tibuch** [comment]
Like the new notebook 'YourOwnData...' very much! Great addition!

Maybe @fjug or @alex-krull wants to look over it as well. I think we could merge.

**Pull request merged**
